#Postgres Local DB
version: '3'
services:
  db_local:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data: